version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:860061945305:task-definition/avitask3:1"
        LoadBalancerInfo:
          ContainerName: "eureka"
          ContainerPort: "8761"
        PlatformVersion: "LATEST"
